### ISSUE TITLE
Question: Side by side panoramas in "locked" and "unlocked" modes

### ISSUE THREAD

**Issue by webpepper** [mistic100/Photo-Sphere-Viewer#381]
I have a question regarding side by side rendering similar to this library:
https://www.marzipano.net/demos/side-by-side/

I _have_ managed to achieve what that examples shows: two panoramas are shown side by side, and when one is dragged the other moves in sync.

My approach:
```js
LEFT_PSV.on('position-updated', (event, position) => {
  RIGHT_PSV.rotate(position);
});
```

I'm not attaching a similar listener on RIGHT_PSV to demonstrate the issue I'm trying to solve.

If `RIGHT_PSV` is first moved independently and then `LEFT_PSV` is dragged/moved, `RIGHT_PSV` **jumps** to the same position as `LEFT_PSV`. I'm trying to figure out if it's possible to avoid this jumping and move RIGHT_PSV _by as much_ as LEFT_PSV has moved. Clearly my approach is not the right one to achieve this. Is there a way or am I reaching too far?

The ultimate goal is to have a "locked" mode in which both images are synced and move together, and an "unlocked" mode in which you can move them independently and then "lock" again. You might want to, for example, adjust the position of one of them first and then rotate at the same time again. 

Video example: https://youtu.be/S_TRvIehd-A

**Comment by mistic100** [comment]
I have no idea how to help you. There is no such level of information emitted by the viewer.
Well you could group two subsequent "position-updated" events (similar to RxJs pairwise operator) and only move the second viewer by the delta.

BTW marzipano seems much more advanced than PhotoSphereViewer

**Comment by webpepper** [comment]
Ah, thanks! You pointed me in the right direction. I tried that quickly (calculating delta) but it didn't work... and then I tried again and after some trial and error I think I got it working. 

Here's my working prototype:
```js
let startXY;
let rotating = false;

LEFT_PSV.on('before-rotate', () => {
  if (rotating) {
    return;
  }

  rotating = true;

  startXY = LEFT_PSV.dataHelper.sphericalCoordsToTextureCoords(
    LEFT_PSV.getPosition()
  );
});

LEFT_PSV.on('position-updated', (event, position) => {
  const currentXY = LEFT_PSV.dataHelper.sphericalCoordsToTextureCoords(position);

  const diffX = startXY.x - currentXY.x;
  const diffY = startXY.y - currentXY.y;

  const rightPosXY = RIGHT_PSV.dataHelper.sphericalCoordsToTextureCoords(RIGHT_PSV.getPosition());

  const newRightPosition = RIGHT_PSV.dataHelper.textureCoordsToSphericalCoords({
    x: rightPosXY.x - diffX,
    y: rightPosXY.y - diffY
  });

  RIGHT_PSV.rotate(newRightPosition);

  rotating = false;
});
```

Video: https://youtu.be/40r_xXICDq8

More testing needs to be done with zoom levels and other parameters but this is a start.

**Comment by mistic100** [comment]
you do not have to call textureCoordsToSphericalCoords before rotate, the rotate methode cappect longitude/latitude or x/y.

But I wonder why you work in texture coordinates, it should be working in spherical coords too and remove the need of constant conversion

you will probably have issues when crossing the 0px mark (or +Pi/-Pi)

**Comment by webpepper** [comment]
> you do not have to call textureCoordsToSphericalCoords before rotate

True that, good catch!

> But I wonder why you work in texture coordinates

I started using x/y because they're integers and it's easier to see when and by how much something changes. `position-updated` and `before-rotate` are called a lot, so it's hard to tell looking at lat/long what the difference is. And with the other issue you mentioned regarding the 0px mark it's easier to work with pixels.

I've added some more code to prevent "over-rotation" of the seconds image. In my case `croppedHeight` and `fullHeight` in panoData are the same, I'm using it to determine when to stop rotating. It addresses _a_ problem but I have a feeling that's not all of it yet.

Basically the second image will remain fixed if its top or bottom have been reached. In the previous version it flipped.

This the first time in a long time I've had to look up geometry, so definitely not an expert in this area :D


```js
LEFT_PSV.on('position-updated', (event, position) => {
  const leftPsvXY = LEFT_PSV.dataHelper.sphericalCoordsToTextureCoords(position);

  const diffX = startXY.x - leftPsvXY.x;
  const diffY = startXY.y - leftPsvXY.y;

  const rightPsvXY = RIGHT_PSV.dataHelper.sphericalCoordsToTextureCoords(
    RIGHT_PSV.getPosition()
  );

  const newX = rightPsvXY.x - diffX;
  let newY = rightPsvXY.y - diffY;

  if (newY > RIGHT_PSV.prop.panoData.croppedHeight) {
    console.log(`Using MAX Y=${RIGHT_PSV.prop.panoData.croppedHeight}`);
    newY = RIGHT_PSV.prop.panoData.croppedHeight;
  } else if (newY < 0) {
    console.log('Using MIN Y=0');
    newY = 0;
  }

  RIGHT_PSV.rotate({
    x: newX,
    y: newY
  });

  rotating = false;
});
```

**Comment by mistic100** [comment]
@webpepper do you need further help ? can this be closed ?

Also if you want you could publish your work as a plugin https://photo-sphere-viewer.js.org/plugins/writing-a-plugin.html

**Comment by webpepper** [comment]
I'm still waiting for user feedback but it might be a while, so we can move on with this issue (close it).

I wasn't able to get rid of "jumping" entirely even with longitude and latitude. It's better but than x and y, but the issue remains. Depending on how images are positioned relative to each other you may or may not notice it. But I know it's not perfect, so I'm going to return to this again. 

It's definitely a case of one image being close to its 0 position (either x or y), adding a delta to it. I guess in a why I'm stuck at trying to create a `rotateBy(someDelta)` method as opposed to `rotate()` (i.e., `rotateTo()`). And making this `rotateBy` work smoothly regardless of where you are in terms of x,y or lat,long.

The solution that I got so far satisfies 90% of the requirements, so it's a "win" for now in any case.

**Comment by mistic100** [comment]
A rotateBy will basically do this https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/services/EventsHandler.js#L606-L609
which you can already do as "prop" is the same object as "Viewer#prop" and is public.

It might help.

**Comment by mistic100** [comment]
(not saying that a rotateBy method won't be a good addition to the lib)
